export * from './drinkmoments.model';
export * from './ota-info.model';
export * from './firm-wares.model';
export * from './automatic-results.model';
export * from './automatic-details.model';
export * from './manual-details.model';
export * from './configurations.model';
export * from './manual-results.model';
export * from './certificates.model';
